{% set name = "rocm-bandwidth-test" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RadeonOpenCompute/rocm_bandwidth_test/archive/roc-{{ version }}.tar.gz
  sha256: 04564d1a7689c8875b330091c8c83f11f1827a8a8c696d15209b5d3d3c9cda44

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - {{ cdt('numactl-devel') }}
    - {{ cdt('pciutils-devel') }}
  host:
    - rocr-runtime {{ version }}
    - roct-thunk-interface {{ version }}
  run:
    - rocr-runtime {{ version }}
    - roct-thunk-interface {{ version }}

test:
  commands:
    # Can't run without an AMD GPU
    - test -f $PREFIX/bin/rocm_bandwidth_test

about:
  home: https://github.com/RadeonOpenCompute/rocm_bandwidth_test
  license: NCSA
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Bandwidth test for ROCm'

extra:
  recipe-maintainers:
    - isuruf
